AWSTemplateFormatVersion: 2010-09-09
Description: Sets Up EKS Cluster
Parameters:

  Client:
    Type: String

  Environment:
    Type: String

Resources:
  
  EKSServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${Client}_${Environment}_eks_role'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEKSServicePolicy'
        - 'arn:aws:iam::aws:policy/AmazonEKSClusterPolicy'
  
  EKSCluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: !Sub ${Client}-${Environment}-eks
      RoleArn: !GetAtt EKSServiceRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - 'Fn::ImportValue': !Sub '${Client}-${Environment}-ControlPlaneSG'
        SubnetIds:
          - 'Fn::ImportValue': !Sub '${Client}-${Environment}-PublicSubnet1'
          - 'Fn::ImportValue': !Sub '${Client}-${Environment}-PublicSubnet2'
          - 'Fn::ImportValue': !Sub '${Client}-${Environment}-PublicSubnet3'

  SsmEksName:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub /EKS_NAME/${Environment}/${Client}
      Value: !Sub ${Client}-${Environment}-eks
      Type: String
